name: Trigger auto deployment for auth-db

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/auth-db-AutoDeployTrigger-2dd2e4a4-7502-427b-969a-800a061ebadc.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: skilldb.azurecr.io
          username: ${{ secrets.AUTHDB_REGISTRY_USERNAME }}
          password: ${{ secrets.AUTHDB_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: skilldb.azurecr.io/auth-db:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AUTHDB_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n auth-db -g afourathon-skill-db-rg --server skilldb.azurecr.io --username  ${{ secrets.AUTHDB_REGISTRY_USERNAME }} --password ${{ secrets.AUTHDB_REGISTRY_PASSWORD }}
            az containerapp update -n auth-db -g afourathon-skill-db-rg --image skilldb.azurecr.io/auth-db:${{ github.sha }}
